name: sunny_day
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  connectivity_plus: 3.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: 9.0.2
  get_it: 7.3.0
  google_fonts: 4.0.4
  google_places_autocomplete_text_field: 0.0.3
  line_icons: 2.0.1
  logger: 1.3.0
  provider: 6.0.5
  shared_preferences: 2.1.0
  weather_app_dart_client:
    git:
      url: https://github.com/TinasheKeith/dart_open_weather_client.git
      ref: main

dev_dependencies:
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter

  very_good_analysis: 4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/backgrounds/
    - assets/icons/
